version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_dashboard_app
    ports:
      - "4200:4200"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/admin-dashboard?schema=public
    command: sh -c "npx -w apps/server prisma generate && npx -w apps/server prisma migrate deploy && npm run prisma:seed-users -w apps/server && npm run start"

    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: admin_dashboard_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin-dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
