import { type HeadCell } from "@/common/components/table/types/head-cell.type";
import { type User } from "@/common/types/types";

export const headCellUsers: HeadCell<User>[] = [
  {
    id: "email",
    numeric: false,
    disablePadding: true,
    label: "Email",
  },
  {
    id: "username",
    numeric: false,
    disablePadding: false,
    label: "Username",
  },
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Name",
  },
  {
    id: "lastName",
    numeric: false,
    disablePadding: false,
    label: "Last Name",
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Role",
  },
  {
    id: "organization",
    numeric: false,
    disablePadding: false,
    label: "Organization",
  },
];

export const users: User[] = [
  {
    id: "b71f2e5d-21e6-4ad3-bf8a-4f3c2a68d7d1",
    email: "alice.admin@example.com",
    username: "alice123",
    name: "Alice",
    lastName: "Anderson",
    role: "ADMIN",
    organization: "TechNova Inc.",
  },
  {
    id: "9a9b5d5e-1f47-42d5-a303-0b3087c43c7b",
    email: "bob.staff@example.com",
    username: "bobby",
    name: "Bob",
    lastName: "Baker",
    role: "STAFF",
    organization: "GreenLeaf Corp.",
  },
  {
    id: "8d23e3e2-5df2-4ea4-a849-d08312e8e66e",
    email: "carla.customer@example.com",
    username: "carla.c",
    name: "Carla",
    lastName: "Castillo",
    role: "COSTUMER",
    organization: "SmartHome Co.",
  },
  {
    id: "d6b6a40b-54b6-4fa7-b3d2-ec1f4a9a1e7c",
    email: "dan.staff@example.com",
    username: "daniel_s",
    name: "Daniel",
    lastName: "Soto",
    role: "STAFF",
    organization: "GreenLeaf Corp.",
  },
  {
    id: "cc1c478f-b2ee-4cbf-8b15-cb2d58a4b7b9",
    email: "emily.admin@example.com",
    username: "em_admin",
    name: "Emily",
    lastName: "Evans",
    role: "ADMIN",
    organization: "TechNova Inc.",
  },
  {
    id: "a8b4ce44-b601-4c11-b77d-00b7f3fa4ef2",
    email: "frank.customer@example.com",
    username: "frankie",
    name: "Frank",
    lastName: "Fernandez",
    role: "COSTUMER",
    organization: "SmartHome Co.",
  },
  {
    id: "0dbce1ed-e1c2-4f90-94b0-12c98923b9b2",
    email: "gina.staff@example.com",
    username: "gina_staff",
    name: "Gina",
    lastName: "Gomez",
    role: "STAFF",
    organization: "BlueOcean Solutions",
  },
  {
    id: "c3e66ff9-5cd1-434f-b842-f2e9dece9b01",
    email: "henry.customer@example.com",
    username: "henry.h",
    name: "Henry",
    lastName: "Hernandez",
    role: "COSTUMER",
    organization: "NextGen Retail",
  },
  {
    id: "27b8cb19-3c60-4f9d-896d-9f98b7b0c4ab",
    email: "isabel.admin@example.com",
    username: "isa_admin",
    name: "Isabel",
    lastName: "Ibarra",
    role: "ADMIN",
    organization: "TechNova Inc.",
  },
  {
    id: "3dc68e2d-50ab-4c55-b361-d67e85c6608d",
    email: "jack.staff@example.com",
    username: "jackstaff",
    name: "Jack",
    lastName: "Jimenez",
    role: "STAFF",
    organization: "BlueOcean Solutions",
  },
];
